package com.skyreserve.controller;
import com.skyreserve.model.*; import com.skyreserve.repo.*; import jakarta.transaction.Transactional; import org.springframework.http.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*; import java.util.stream.Collectors;
@RestController @RequestMapping("/api") @CrossOrigin public class ApiController { final UserRepository users; final FlightRepository flights; final BookingRepository bookings; final BCryptPasswordEncoder enc; public ApiController(UserRepository u,FlightRepository f,BookingRepository b,BCryptPasswordEncoder e){users=u;flights=f;bookings=b;enc=e;}
@GetMapping("/flights") public List<Flight> flights(@RequestParam(required=false)String origin,@RequestParam(required=false)String destination,@RequestParam(required=false)LocalDate date){if(origin!=null&&destination!=null&&date!=null)return flights.findByOriginIgnoreCaseAndDestinationIgnoreCaseAndDate(origin,destination,date);return flights.findAll();}
@GetMapping("/flights/{id}/seats") public List<String> seats(@PathVariable Long id){Flight f=flights.findById(id).orElseThrow();Set<String> taken=bookings.findAll().stream().filter(b->id.equals(b.getFlightId())&&"CONFIRMED".equals(b.getStatus())).map(Booking::getSeat).collect(Collectors.toSet());List<String> out=new ArrayList<>();for(int r=1;r<=f.getRows();r++)for(int c=0;c<f.getCols();c++){String s=r+""+(char)('A'+c);if(!taken.contains(s))out.add(s);}return out;}
@PostMapping("/signup") public ResponseEntity<?> signup(@RequestBody Map<String,String>x){if(users.findByEmail(x.get("email")).isPresent())return ResponseEntity.badRequest().body(Map.of("message","Email already registered"));User u=new User();u.setName(x.get("name"));u.setEmail(x.get("email"));u.setPassword(enc.encode(x.get("password")));users.save(u);return ResponseEntity.ok(Map.of("message","Account created","email",u.getEmail(),"role","USER"));}
@PostMapping("/login") public ResponseEntity<?> login(@RequestBody Map<String,String>x){return users.findByEmail(x.get("email")).filter(u->enc.matches(x.get("password"),u.getPassword())).<ResponseEntity<?>>map(u->ResponseEntity.ok(Map.of("message","Login successful","name",u.getName(),"email",u.getEmail(),"role",u.getRole()))).orElseGet(()->ResponseEntity.status(401).body(Map.of("message","Invalid email or password")));}
@PostMapping("/bookings") @Transactional public ResponseEntity<?> book(@RequestBody Map<String,Object>x){Long fid=Long.valueOf(x.get("flightId").toString());String seat=x.get("seat").toString();Flight f=flights.findById(fid).orElseThrow();if(bookings.existsByFlightIdAndSeatAndStatus(fid,seat,"CONFIRMED"))return ResponseEntity.status(409).body(Map.of("message","Seat already booked. Please choose another seat."));Booking b=new Booking();b.setBookingCode("SR"+(System.currentTimeMillis()%100000000));b.setFlightId(fid);b.setSeat(seat);b.setPassenger(x.get("passenger").toString());b.setEmail(x.get("email").toString());b.setAmount(f.getPrice());b.setStatus("CONFIRMED");b.setPaymentStatus("PAID");b.setBookedAt(LocalDateTime.now());bookings.save(b);return ResponseEntity.ok(b);}
@GetMapping("/bookings") public List<Booking> my(@RequestParam String email){return bookings.findByEmailOrderByBookedAtDesc(email);}@GetMapping("/bookings/{code}") public Booking one(@PathVariable String code){return bookings.findByBookingCode(code).orElseThrow();}@GetMapping("/admin/bookings") public List<Booking> admin(){return bookings.findAll();}@GetMapping("/admin/users") public List<User> adminUsers(){return users.findAll();}}
